#!/bin/sh
 setenv  PATH "/scratch/rchamant/prod/pls_33266325/isd/bin:/arudev/tech-stack/oel6new/portable/bin:.:/arudev/tech-stack/oel6new/portable/bin:/arudev/tech-stack/oel6new/linux/bin:/scratch/rchamant/prod/pls_33266325/isdev/dba/bin:/scratch/rchamant/prod/pls_33266325/isd/bin:/arudev/bin:/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin:/scratch/rchamant/prod/pls_33266325/isd_qa/bin:/arudev/oracle/12.1.0.2.0/bin:/arudev/tech-stack/oel6new/portable/bin:.:/arudev/tech-stack/oel6new/portable/bin:/arudev/tech-stack/oel6new/linux/bin:/scratch/rchamant/prod/pls_33266325/isdev/dba/bin:/scratch/rchamant/prod/pls_33266325/isd/bin:/arudev/bin:/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin:/scratch/rchamant/prod/pls_33266325/isd_qa/bin/:$PATH "
 setenv  SHLVL "2 "
 setenv  PWD "/scratch/rchamant/prod/pls_33266325 "
 setenv  ARU_HOME "/scratch/rchamant/prod/pls_33266325/isd "
 setenv  ISD_TECH_STACK "/arudev/tech-stack/oel6new/linux "
 setenv  ISDDBA_HOME "/scratch/rchamant/prod/pls_33266325/isdev/dba "
 setenv  COMMON_PATH "/arudev/tech-stack/oel6new/portable/bin:.:/arudev/tech-stack/oel6new/portable/bin:/arudev/tech-stack/oel6new/linux/bin:/scratch/rchamant/prod/pls_33266325/isdev/dba/bin:/scratch/rchamant/prod/pls_33266325/isd/bin:/arudev/bin:/usr/local/bin:/bin:/sbin:/usr/bin:/usr/sbin:/scratch/rchamant/prod/pls_33266325/isd_qa/bin "
 setenv  MANPATH "/arudev/tech-stack/oel6new/portable/share/man:/arudev/tech-stack/oel6new/portable/man:/arudev/tech-stack/oel6new/linux/share/man:/arudev/tech-stack/oel6new/linux/man:/arudev/man:/arudev/tools/share/man:/usr/share/man:/usr/local/share/man "
 setenv  LD_LIBRARY_PATH_BASE "/lib:/usr/lib:/arudev/tech-stack/oel6new/linux/lib:/arudev/tech-stack/oel6new/linux/lib64 "
 setenv  TWO_TASK "aru_ade_qa "
 setenv  LD_LIBRARY_PATH "/arudev/oracle/12.1.0.2.0/lib:/lib:/usr/lib:/arudev/tech-stack/oel6new/linux/lib:/arudev/tech-stack/oel6new/linux/lib64 "
 setenv  PERL5LIB "/scratch/rchamant/prod/pls_33266325/isd/pm "
 setenv  SQLPATH "/arudev/env:/scratch/rchamant/prod/pls_33266325/isd/plsql/dba:/arudev/oracle/12.1.0.2.0:/scratch/rchamant/prod/pls_33266325/isdev/dba/sql:/scratch/rchamant/prod/pls_33266325/isd/sql/isd:/scratch/rchamant/prod/pls_33266325/isd/plsql/isd:/scratch/rchamant/prod/pls_33266325/isd/sql/aru:/scratch/rchamant/prod/pls_33266325/isd/plsql/aru:/scratch/rchamant/prod/pls_33266325/isd/sql/pts:/scratch/rchamant/prod/pls_33266325/isd/plsql/pts:/scratch/rchamant/prod/pls_33266325/isd/sql/urs:/scratch/rchamant/prod/pls_33266325/isd/plsql/urs:/scratch/rchamant/prod/pls_33266325/isd/sql/autobuild:/scratch/rchamant/prod/pls_33266325/isd/plsql/autobuild:/scratch/rchamant/prod/pls_33266325/isd/sql/rme:/scratch/rchamant/prod/pls_33266325/isd/plsql/rme:/scratch/rchamant/prod/pls_33266325/isd/sql/urm:/scratch/rchamant/prod/pls_33266325/isd/plsql/urm:/scratch/rchamant/prod/pls_33266325/isd/sql/tpt:/scratch/rchamant/prod/pls_33266325/isd/plsql/tpt:/scratch/rchamant/prod/pls_33266325/isd/sql/gscc:/scratch/rchamant/prod/pls_33266325/isd/plsql/gscc:/scratch/rchamant/prod/pls_33266325/isd/sql/apex:/scratch/rchamant/prod/pls_33266325/isd/plsql/apex:/scratch/rchamant/prod/pls_33266325/isd/sql/ords:/scratch/rchamant/prod/pls_33266325/isd/plsql/ords "
 setenv  APF_BASE_HOME "/scratch/rchamant/prod/pls_33266325/isd "
 setenv  APF_BASE "/scratch/rchamant/prod/pls_33266325/isd "
 setenv  ISD_GIT_REPOSITORY "/scratch/rchamant/prod/pls_33266325 "
 setenv  ISD_GIT_REPO_NAME "prod/pls_33266325 "
 setenv  ISDEV_HOME "/scratch/rchamant/prod/pls_33266325/isdev "
 setenv  ISD_QA_HOME "/scratch/rchamant/prod/pls_33266325/isd_qa "
 setenv  ISD_UPG_HOME "/scratch/rchamant/prod/pls_33266325/isd_upg "
 setenv  PLS_HOME "/scratch/rchamant/prod/pls_33266325 "
 setenv  JDEV_USER_HOME "/scratch/rchamant/prod/pls_33266325 "
 setenv  ARUDB_CONNECT "aru/aru "
 setenv  APF_DEBUG "on skip_make_apply_dbdrv test_rules mail skip_install skip_farm "
 setenv  ARUFTPD_DEBUG "on "
 setenv  ARUFTPD_PTS_PASSWORD "ptspass "
 setenv  ARUFTPD_MODE "internal "
 setenv  WEBAPP_DEBUG "stderr truncate_cgi OraDB "
 setenv  MAIL_MODE "test "
 setenv  PTS_DEBUG "adpatch adadmin admin tm env "
 setenv  ANT_HOME "/arudev/tech-stack/oel6new/portable "
 setenv  M2_HOME "/arudev/tech-stack/oel6new/portable "
 setenv  ISD_GIT_BRANCH "feature/rchamant_bug-33266325_sprint_searu2109_Issue_with_Bootstrap_Content_feature_of_CPM_rest_API "
 setenv  ISD_GIT_PARENT_BRANCH "sprint/searu2109 "
 setenv  CVS_RSH "ssh "
 setenv  SSH_ASKPASS "/usr/libexec/openssh/gnome-ssh-askpass "
 setenv  KDEDIRS "/usr "
 setenv  QT_PLUGIN_PATH "/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins "
 setenv  LESSOPEN "||/usr/bin/lesspipe.sh %s "
 setenv  MODULESHOME "/usr/share/Modules "
 setenv  MODULEPATH "/usr/share/Modules/modulefiles:/etc/modulefiles "
 setenv  LOADEDMODULES " "
 setenv  QTDIR "/usr/lib64/qt-3.3 "
 setenv  QTINC "/usr/lib64/qt-3.3/include "
 setenv  QTLIB "/usr/lib64/qt-3.3/lib "
 setenv  QT_GRAPHICSSYSTEM_CHECKED "1 "
 setenv  ISD_HOME "/scratch/rchamant/prod/pls_33266325/isd"